### ISSUE TITLE
Running on Google Colab, create_link error occurs.

### ISSUE THREAD

**Issue by Michi-123** [arnab39/cycleGAN-PyTorch#3]
I run main.py on Google Colab , and I got the message bellow.

`  File "/content/grive/My Drive/CycleGAN/cycleGAN-PyTorch/utils.py", line 37, in create_link
    os.path.join(dirs[key], 'Link'))
OSError: [Errno 95] Operation not supported: '/content/grive/My Drive/CycleGAN/cycleGAN-PyTorch/datasets/horse2zebra/trainA' -> './datasets/horse2zebra/ltrainA/Link'`

I think it's better to copy trainA to ltrainA without using the link.

**Comment by Michi-123** [comment]
But why do you use link?

**Comment by arnab39** [comment]
Yeah, you can do that. I never tried running this code on google colab.

**Comment by Michi-123** [comment]
Thanks a lot.

**Comment by nahidpranto** [comment]
> 
> 
> I run main.py on Google Colab , and I got the message bellow.
> 
> ` File "/content/grive/My Drive/CycleGAN/cycleGAN-PyTorch/utils.py", line 37, in create_link os.path.join(dirs[key], 'Link')) OSError: [Errno 95] Operation not supported: '/content/grive/My Drive/CycleGAN/cycleGAN-PyTorch/datasets/horse2zebra/trainA' -> './datasets/horse2zebra/ltrainA/Link'`
> 
> I think it's better to copy trainA to ltrainA without using the link.

only copying images would help from this problem?
