### ISSUE TITLE
Is this mode collapse?

### ISSUE THREAD

**Issue by Michi-123** [arnab39/cycleGAN-PyTorch#4]
Do you think this is mode collapse? (Training: 50%  epoch: 100/200)
[horse2zebra](https://photos.app.goo.gl/ubQ5yXLVfuFpguSi6)

I want to know how to Improve this problem, thanks.

**Comment by arnab39** [comment]
Hey,
Did you try training until 200 epochs?

**Comment by Michi-123** [comment]
Yes, I did. It appears from less than 100 epochs on my original train datasets.
